package com.cmcc.csb.sb_iap_checktokenkeyinsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-17T16:15:47.469+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://csb.cmcc.com/SB_IAP_CheckTokenKeyInSrv", name = "SB_IAP_CheckTokenKeyInSrv")
@XmlSeeAlso({ObjectFactory.class, com.cmcc.mss.msgheader.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBIAPCheckTokenKeyInSrv {

    @WebResult(name = "SB_IAP_CheckTokenKeyInSrvResponse", targetNamespace = "http://csb.cmcc.com/SB_IAP_CheckTokenKeyInSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBIAPCheckTokenKeyInSrvResponse process(
        @WebParam(partName = "payload", name = "SB_IAP_CheckTokenKeyInSrvRequest", targetNamespace = "http://csb.cmcc.com/SB_IAP_CheckTokenKeyInSrv")
        SBIAPCheckTokenKeyInSrvRequest payload
    );
}
