package com.cmcc.csb.sb_iap_pageinquiryuserinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-17T17:05:54.171+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://csb.cmcc.com/SB_IAP_PageInquiryUserInfoSrv", name = "SB_IAP_PageInquiryUserInfoSrv")
@XmlSeeAlso({com.cmcc.mss.msgheader.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBIAPPageInquiryUserInfoSrv {

    @WebResult(name = "SB_IAP_PageInquiryUserInfoSrvResponse", targetNamespace = "http://csb.cmcc.com/SB_IAP_PageInquiryUserInfoSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBIAPPageInquiryUserInfoSrvResponse process(
        @WebParam(partName = "payload", name = "SB_IAP_PageInquiryUserInfoSrvRequest", targetNamespace = "http://csb.cmcc.com/SB_IAP_PageInquiryUserInfoSrv")
        SBIAPPageInquiryUserInfoSrvRequest payload
    );
}
