
package com.cmcc.csb.sb_iap_managertasktodosrv;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-06-03T14:25:41.357+08:00
 * Generated source version: 2.7.18
 * 
 */
 
public class SBIAPManagerTaskToDoSrv_SBIAPManagerTaskToDoSrvPort_Server{

    protected SBIAPManagerTaskToDoSrv_SBIAPManagerTaskToDoSrvPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SBIAPManagerTaskToDoSrvImpl();
        String address = "http://soa.nfjd.gmcc.net:8011/NFJD/ProxyService/IAP/SB_IAP_ManagerTaskToDoSrv/SB_IAP_ManagerTaskToDoSrv";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SBIAPManagerTaskToDoSrv_SBIAPManagerTaskToDoSrvPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
