package com.cmcc.csb.sb_iap_managertasktodosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-06-03T14:25:41.347+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://csb.cmcc.com/SB_IAP_ManagerTaskToDoSrv", name = "SB_IAP_ManagerTaskToDoSrv")
@XmlSeeAlso({com.cmcc.mss.msgheader.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBIAPManagerTaskToDoSrv {

    @WebResult(name = "SB_IAP_ManagerTaskToDoSrvResponse", targetNamespace = "http://csb.cmcc.com/SB_IAP_ManagerTaskToDoSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBIAPManagerTaskToDoSrvResponse process(
        @WebParam(partName = "payload", name = "SB_IAP_ManagerTaskToDoSrvRequest", targetNamespace = "http://csb.cmcc.com/SB_IAP_ManagerTaskToDoSrv")
        SBIAPManagerTaskToDoSrvRequest payload
    );
}
