package com.cmcc.csb.sb_iap_inquiryouinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-17T15:39:26.944+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://csb.cmcc.com/SB_IAP_InquiryOUInfoSrv", name = "SB_IAP_InquiryOUInfoSrv")
@XmlSeeAlso({ObjectFactory.class, com.cmcc.mss.msgheader.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBIAPInquiryOUInfoSrv {

    @WebResult(name = "SB_IAP_InquiryOUInfoSrvResponse", targetNamespace = "http://csb.cmcc.com/SB_IAP_InquiryOUInfoSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBIAPInquiryOUInfoSrvResponse process(
        @WebParam(partName = "payload", name = "SB_IAP_InquiryOUInfoSrvRequest", targetNamespace = "http://csb.cmcc.com/SB_IAP_InquiryOUInfoSrv")
        SBIAPInquiryOUInfoSrvRequest payload
    );
}
