package com.cmcc.csb.sb_iap_sendmailinfosrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-14T13:33:33.054+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://csb.cmcc.com/SB_IAP_SendMailInfoSrv", name = "SB_IAP_SendMailInfoSrv")
@XmlSeeAlso({com.cmcc.mss.msgheader.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBIAPSendMailInfoSrv {

    @WebResult(name = "SB_IAP_SendMailInfoSrvResponse", targetNamespace = "http://csb.cmcc.com/SB_IAP_SendMailInfoSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBIAPSendMailInfoSrvResponse process(
        @WebParam(partName = "payload", name = "SB_IAP_SendMailInfoSrvRequest", targetNamespace = "http://csb.cmcc.com/SB_IAP_SendMailInfoSrv")
        SBIAPSendMailInfoSrvRequest payload
    );
}
