package com.cmcc.csb.sb_iap_ssologininsrv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-17T15:10:41.266+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://csb.cmcc.com/SB_IAP_SSOLoginInSrv", name = "SB_IAP_SSOLoginInSrv")
@XmlSeeAlso({com.cmcc.mss.msgheader.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SBIAPSSOLoginInSrv {

    @WebResult(name = "SB_IAP_SSOLoginInSrvResponse", targetNamespace = "http://csb.cmcc.com/SB_IAP_SSOLoginInSrv", partName = "payload")
    @WebMethod(action = "process")
    public SBIAPSSOLoginInSrvResponse process(
        @WebParam(partName = "payload", name = "SB_IAP_SSOLoginInSrvRequest", targetNamespace = "http://csb.cmcc.com/SB_IAP_SSOLoginInSrv")
        SBIAPSSOLoginInSrvRequest payload
    );
}
